<?php
if (!defined('init_pages')) { header('HTTP/1.0 404 not found'); exit; }
$TPL->SetTitle('Armory');
$TPL->LoadHeader();
function arm_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function arm_race($id){$a=array(1=>'Human',2=>'Orc',3=>'Dwarf',4=>'Night Elf',5=>'Undead',6=>'Tauren',7=>'Gnome',8=>'Troll',10=>'Blood Elf',11=>'Draenei');return isset($a[(int)$id])?$a[(int)$id]:'Unknown';}
function arm_class($id){$a=array(1=>'Warrior',2=>'Paladin',3=>'Hunter',4=>'Rogue',5=>'Priest',6=>'Death Knight',7=>'Shaman',8=>'Mage',9=>'Warlock',11=>'Druid');return isset($a[(int)$id])?$a[(int)$id]:'Unknown';}
$q=isset($_GET['q'])?trim($_GET['q']):''; $realm=isset($_GET['realm'])?(int)$_GET['realm']:1; if($realm<=0)$realm=1; $results=array();
if($q!=='' && isset($realms_config[$realm])){ try{ $db=$CORE->RealmDatabaseConnection($realm); if($db){ $s=$db->prepare('SELECT guid,account,name,race,class,level,online,totaltime,totalKills FROM characters WHERE name LIKE :q ORDER BY level DESC,name ASC LIMIT 50'); $s->execute(array(':q'=>'%'.$q.'%')); $results=$s->fetchAll(PDO::FETCH_ASSOC); } }catch(Exception $e){$results=array();} }
?>
<style>
.arm-wrap{padding:28px 42px 42px;text-align:left;color:#cfc4a8}.arm-panel{background:rgba(0,0,0,.32);border:1px solid rgba(212,175,55,.16);border-radius:9px;padding:22px;margin-bottom:20px}.arm-title{font-family:Georgia,serif;color:#d4af37;font-size:28px;margin:0 0 10px}.arm-form{display:grid;grid-template-columns:1fr 170px 130px;gap:12px;margin-top:18px}.arm-form input,.arm-form select{background:#0b0b0b;border:1px solid rgba(212,175,55,.22);border-radius:6px;color:#d8caa7;padding:12px}.arm-form button{background:linear-gradient(#d7b842,#9f741a);border:0;border-radius:6px;color:#1b1207;font-weight:bold}.arm-results{display:grid;gap:10px}.arm-row{display:grid;grid-template-columns:1fr 160px 130px 100px;gap:12px;align-items:center;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.06);border-radius:8px;padding:14px 16px;text-decoration:none!important;color:#cfc4a8!important}.arm-row:hover{border-color:rgba(212,175,55,.42);background:rgba(212,175,55,.06)}.arm-name{color:#d4af37;font-size:18px}.arm-muted{color:#8c816d}.arm-online{color:#4bd66b}.arm-offline{color:#b76a5c}@media(max-width:700px){.arm-form,.arm-row{grid-template-columns:1fr}}
</style>
<div class="content_holder"><div class="sub-page-title"><div id="title"><h1>Armory<p></p><span></span></h1></div></div><div class="container_2 account" align="center"><div class="cont-image"><div class="container_3 account_sub_header"><div class="grad"><div class="page-title">Character Armory</div><a href="<?php echo arm_h($config['BaseURL']); ?>/index.php">Back to home</a></div></div><div class="arm-wrap"><div class="arm-panel"><h2 class="arm-title">Search Characters</h2><p class="arm-muted">Find an in-game character and inspect profile, gear, gold, playtime and achievements.</p><form class="arm-form" method="get"><input type="hidden" name="page" value="armory"><input type="text" name="q" value="<?php echo arm_h($q); ?>" placeholder="Character name"><select name="realm"><?php foreach($realms_config as $id=>$r): ?><option value="<?php echo (int)$id; ?>" <?php echo $realm===(int)$id?'selected':''; ?>><?php echo arm_h($r['name']); ?></option><?php endforeach; ?></select><button type="submit">Search</button></form></div><div class="arm-panel"><h2 class="arm-title">Results</h2><?php if($q===''): ?><div class="arm-muted">Enter a character name to start searching.</div><?php elseif(!$results): ?><div class="arm-muted">No characters found.</div><?php else: ?><div class="arm-results"><?php foreach($results as $r): ?><a class="arm-row" href="<?php echo arm_h($config['BaseURL']); ?>/index.php?page=profile&uid=<?php echo (int)$r['account']; ?>&char=<?php echo (int)$r['guid']; ?>&realm=<?php echo (int)$realm; ?>"><div><div class="arm-name"><?php echo arm_h($r['name']); ?></div><div class="arm-muted">Level <?php echo (int)$r['level']; ?> <?php echo arm_h(arm_race($r['race']).' '.arm_class($r['class'])); ?></div></div><div>Total kills: <?php echo (int)$r['totalKills']; ?></div><div>Played: <?php echo floor((int)$r['totaltime']/86400); ?>d</div><div class="<?php echo (int)$r['online']===1?'arm-online':'arm-offline'; ?>"><?php echo (int)$r['online']===1?'Online':'Offline'; ?></div></a><?php endforeach; ?></div><?php endif; ?></div></div></div></div></div>
<?php $TPL->LoadFooter(); ?>